language: python
python:
    - "2.6"
    - "2.7"
    - "pypy"
    - "3.3"
    - "3.4"

before_install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
    - pip install -r requirements.txt
    - pip install -r test-requirements.txt

install:
    - python setup.py bdist_egg
    - pip install -e file://$TRAVIS_BUILD_DIR

script: python setup.py test
